Added Copy Button in Qr Code
tarnas14/ti4-companion pull request #22
Opened 2021-09-14 17:35 UTC by Ronald-patrick

2021-09-14 18:18 UTC, tarnas14 commented
hey, thank you for your contribution! it works exactly as I imagined :)

some feedback:

1. please remove `package-lock.json` from the PR, there's already a `yarn.lock`, because `yarn` is now the standard package manager for create-react-app (which was used to start the client repo)

more general advice:
- when you're working on an issue, you can reference it in commit message or PR description, like this: #11 <- this will link the PR to the issue. (additionally, if you include text `closes #11`, merging the PR will automatically close the issue)
- it's generally a good practice in OSS to describe in the PR description what has been done. For UI-related tasks it is also nice to provide a screenshot or a recording of the result

2021-09-14 18:20 UTC, tarnas14 requested changes
please remove `package-lock.json` from the PR, there's already a `yarn.lock`, because `yarn` is now the standard package manager for create-react-app (which was used to start the client repo)

2021-09-15 03:08 UTC, Ronald-patrick commented
Thanks for the Guidance, I understood how the github works now.

2021-09-15 03:13 UTC, Ronald-patrick commented
Deleted package-lock.json.

2021-09-15 06:31 UTC, tarnas14 requested changes
whoops, I missed the console.log yesterday, but this is a perfect opportunity for using a 'suggestion' in comment - you can suggest changes in PRs and github allows committing them without leaving the browser :D
please commit the suggestion and I will merge the PR

once again thank you for your contribution!

2021-09-15 06:31 UTC, tarnas14 commented on client/src/SessionView/ShareButton.js
> +		console.log(e.target);
```suggestion
```

please remove console.log :) sorry I missed it in the previous pass

2021-09-15 08:47 UTC, Ronald-patrick commented
Wow that was awesome !

2021-09-15 08:51 UTC, Ronald-patrick commented
Also i wanted to ask that it's giving me the same error as before if i run the react app using my terminal, But when i run in docker it is running fine, but the problem is i have to restart the whole react app in docker to see the changes i made in code as the changes are not reflected in page directly it takes too much time.

2021-09-15 09:02 UTC, tarnas14 approved these changes

2021-09-15 09:04 UTC, tarnas14 commented
// I approved the PR, I'll merge it when we finish the docker discussion

what OS are you using?
the docker-compose and react docker are made to watch file changes made on the system, so no restart should be required
is the hot-reload not working at all, or does it take time?

2021-09-15 09:07 UTC, Ronald-patrick commented
I am using windows

2021-09-15 09:08 UTC, Ronald-patrick commented
Hot restart is happening but it takes too much time for a single change

2021-09-15 09:10 UTC, Ronald-patrick commented
Thank you for Approving my PR !

2021-09-15 09:48 UTC, tarnas14 commented
could you prepare [an issue](https://github.com/tarnas14/ti4-companion/issues/new) - explain your setup and what problems you are experiencing?

I'm not saying I'll fix it, because I'm using linux, but if you have time and motivation you could try and solve it and prepare another PR :D

2021-09-15 11:55 UTC, Ronald-patrick commented
Actually it is a local issue, I there is an actual need I'll add an issue . Also Can you merge the pull request ?

2021-09-15 12:00 UTC, tarnas14 commented
merging right now, I wanted to finish the discussion about your docker problems, thank you for your contribution <3

2021-09-15 12:00 UTC, merged